### ISSUE TITLE
install_requires shouldn't reference Django itself

### ISSUE THREAD

**Issue by andybak** [caioariede/django-location-field#47]
Currently pip installing django-location-field downgrades Django itself:

    $ pip install django-location-field
    Installing collected packages: Django, django-location-field
      Found existing installation: Django 1.9.2
        Uninstalling Django-1.9.2:
          Successfully uninstalled Django-1.9.2
    Successfully installed Django-1.8.9 django-location-field-1.6.1

Even if django-location-field really doesn't work on Django 1.9 this is still surprising behaviour. See similar discussions:

   https://github.com/charettes/django-admin-enhancer/issues/23

   https://github.com/carljm/django-model-utils/issues/183

(yeah - it's me each time ;-) )

**Comment by jackappleby** [comment]
+1. Just installed the package but immediately uninstalled it because of the auto-downgrade from Django 1.9 to 1.8. Not come across a package that does this before. Packages probably shouldn't mess with the currently installed Django version, even if they're not compatible?

**Comment by ezegolub** [comment]
+1. AFAIK you can install it and then install django 1.9 on top of it, dunno how that will play out with requirements.txt. Any chance of getting just that modified as a new version? I mean, remove the django < 1.9 requiremnt in setup.py

**Comment by caioariede** [comment]
Absolutely. I'll be releasing a new version this week.
Em 29 de fev de 2016 11:54, "Ezequiel Golub" <notifications@github.com>
escreveu:

**Comment by caioariede** [comment]
Now there's only a hard dependency for Django 1.7+. I released it with the new version on PyPI: 2.0.0b0

**Comment by andybak** [comment]
This doesn't resolve the issue. Django shouldn't be in there at all. Django isn't a dependency of location-field in any useful sense. Having it in setup.py doesn't help anyone and only causes problems.

There are cases where pip installing location-field will still upgrade Django unexpectedly. Admittedly this is often due to bad practice with pip but it's still easily solved by removing any reference to Django from your setup.py.

If you want to check for Django version compatibility then it's much better to use the system check framework: https://docs.djangoproject.com/en/1.9/ref/checks/

**Comment by caioariede** [comment]
@andybak could you please point me out in which causes it will install Django unexpectedly?

The System Check Framework is a good point.

**Comment by andybak** [comment]
Let's say I've got this in my requirements.txt:

    django==1.8.1
   django-location-field==1.9

I want to upgrade location field. I might type: "pip install django-location-field -U" with the intention of updating requirements.txt once I've tested the new version. If I'm not paying attention, Django gets updated and things break

Basically - anything that involves pip -U on location field will upgrade Django. You might argue I shouldn't be calling pip -U unless I'm running it on my entire requirements.txt. That's reasonable. However - django-location-field has no business touching Django at all. Including it isn't going to help the hypothetical user who tries to use django-location-field with Django 1.6 - they need a warning rather than having their Django install automatically upgraded. That's unlikely to help them sort out the problem :-)
