### ISSUE TITLE
Marker icon not showing on map

### ISSUE THREAD

**Issue by axelwehner** [caioariede/django-location-field#49]
I installed the current Beta version: 2.0.0b0 via pip and use it with Django 1.9.4.
When editing an item with the new location field, the marker icon isn't loading and i get a 404 response for it.

It tries to load the icon from `/static/location_field/images/marker-icon.png` but as I checked the image file in the location_field folder I noticed that it's named `marker-icon-2x.png`.

I tried to rename it to `marker-icon.png` and the 404 disappears, but the icon isn't showing on the map either.

**Comment by sysint64** [comment]
I have the same problem

**Comment by voodmania** [comment]
I was able to solve this issue using the CSS code provided by [SO answer](http://stackoverflow.com/a/27560956/1738761). The correct marker icon to use is [this](http://cdn.leafletjs.com/leaflet/v0.7.7/images/marker-icon.png).

Now it works perfectly.

**Comment by caioariede** [comment]
Fixed in https://github.com/caioariede/django-location-field/pull/53

**Comment by fallenflint** [comment]
Seems that the bug is still there. marker-icon-2x.png should be renamed to marker-icon.png
